name: Do Security
on: pull_request

jobs: 
Run_Security:
  strategy:
    fail-fast: false
    matrix:
      language: [ 'csharp' ]
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{matrix.language}}

    - name: Autobuild
      uses: github/codeql-action/autobuild@v1
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
